import type { SeedWord } from "./types.js";

export const additionalSeedWords: SeedWord[] = [
  // Everyday German
  {
    word: "Steckdose",
    article: "die",
    plural: "Steckdosen",
    english: "electrical socket; power outlet",
    level: "A2",
    meaning: "A fixed connection in a wall from which an electrical device can receive power.",
    exampleDe: "Gibt es hier eine Steckdose für mein Ladegerät?",
    exampleEn: "Is there a power outlet here for my charger?",
    category: "everyday",
    notes: "A Stecker is the plug that goes into the Steckdose.",
  },
  {
    word: "Bürgersteig",
    article: "der",
    plural: "Bürgersteige",
    english: "pavement; sidewalk",
    level: "A2",
    meaning: "The part of a street intended for people walking beside the roadway.",
    exampleDe: "Bitte stell das Fahrrad nicht auf den Bürgersteig.",
    exampleEn: "Please don't leave the bicycle on the pavement.",
    category: "everyday",
    notes: "Gehweg is another common word with the same meaning.",
  },
  {
    word: "Kleingeld",
    article: "das",
    plural: null,
    english: "loose change; small coins",
    level: "A2",
    meaning: "Coins of relatively low value carried for small payments.",
    exampleDe: "Hast du Kleingeld für den Parkautomaten?",
    exampleEn: "Do you have any change for the parking meter?",
    category: "everyday",
    notes: "Usually used as an uncountable collective noun.",
  },
  {
    word: "Wasserkocher",
    article: "der",
    plural: "Wasserkocher",
    english: "electric kettle",
    level: "A2",
    meaning: "An electrical appliance used to boil water quickly.",
    exampleDe: "Der Wasserkocher steht neben der Kaffeemaschine.",
    exampleEn: "The electric kettle is next to the coffee machine.",
    category: "everyday",
    notes: "Literally: water boiler.",
  },
  {
    word: "Mülltrennung",
    article: "die",
    plural: null,
    english: "waste sorting; rubbish separation",
    level: "B1",
    meaning: "The practice of separating waste into categories for recycling and disposal.",
    exampleDe: "Bei der Mülltrennung kommt das Glas in einen eigenen Container.",
    exampleEn: "When sorting waste, glass goes into a separate container.",
    category: "everyday",
    notes: "A useful word when learning how bins work in Germany.",
  },
  {
    word: "Hausflur",
    article: "der",
    plural: "Hausflure",
    english: "communal hallway; entrance hall",
    level: "B1",
    meaning: "The shared corridor or entrance area inside an apartment building.",
    exampleDe: "Im Hausflur dürfen keine Fahrräder stehen.",
    exampleEn: "Bicycles must not be left in the communal hallway.",
    category: "everyday",
    notes: "Flur can also mean a hallway inside an individual home.",
  },
  {
    word: "Pfandbon",
    article: "der",
    plural: "Pfandbons",
    english: "deposit-return receipt",
    level: "B1",
    meaning: "The voucher printed by a bottle-return machine for the deposit value of returned containers.",
    exampleDe: "Ich habe vergessen, den Pfandbon an der Kasse einzulösen.",
    exampleEn: "I forgot to redeem the bottle-deposit receipt at the checkout.",
    category: "everyday",
    notes: "Pfand is the refundable deposit paid on many bottles and cans.",
  },
  {
    word: "Fahrgemeinschaft",
    article: "die",
    plural: "Fahrgemeinschaften",
    english: "carpool; lift-sharing group",
    level: "B1",
    meaning: "A group of people who regularly share a car journey.",
    exampleDe: "Wir bilden eine Fahrgemeinschaft zur Arbeit.",
    exampleEn: "We carpool to work.",
    category: "everyday",
    notes: "The related verb is mitfahren – to travel with someone.",
  },
  {
    word: "Übergangsjacke",
    article: "die",
    plural: "Übergangsjacken",
    english: "light jacket for between seasons",
    level: "B1",
    meaning: "A jacket worn during mild weather between the hot and cold seasons.",
    exampleDe: "Für den Frühling reicht eine Übergangsjacke.",
    exampleEn: "A light jacket is enough for spring.",
    category: "everyday",
    notes: "A very German compound for an oddly specific but familiar item of clothing.",
  },
  {
    word: "Ohrwurm",
    article: "der",
    plural: "Ohrwürmer",
    english: "earworm; catchy tune",
    level: "B1",
    meaning: "A melody that repeatedly plays in your mind and is difficult to forget.",
    exampleDe: "Dieses Lied ist ein echter Ohrwurm.",
    exampleEn: "This song is a real earworm.",
    category: "everyday",
    notes: "The literal meaning is earwig, the insect.",
  },

  // Useful verbs
  {
    word: "sich erkundigen",
    article: null,
    plural: null,
    english: "to enquire; to ask for information",
    level: "B1",
    meaning: "To actively obtain information about a person, place, service, or situation.",
    exampleDe: "Ich möchte mich nach den Öffnungszeiten erkundigen.",
    exampleEn: "I'd like to enquire about the opening hours.",
    category: "verb",
    notes: "Often used with nach + dative: sich nach etwas erkundigen.",
  },
  {
    word: "nachvollziehen",
    article: null,
    plural: null,
    english: "to understand; to follow someone's reasoning",
    level: "B2",
    meaning: "To understand how someone reached a conclusion or why they feel or act a certain way.",
    exampleDe: "Ich kann deine Entscheidung gut nachvollziehen.",
    exampleEn: "I can understand your decision very well.",
    category: "verb",
    notes: "Separable verb: ich vollziehe nach; ich habe nachvollzogen.",
  },
  {
    word: "sich einigen",
    article: null,
    plural: null,
    english: "to reach an agreement",
    level: "B1",
    meaning: "To arrive at a shared decision after discussion or disagreement.",
    exampleDe: "Wir haben uns auf einen Termin geeinigt.",
    exampleEn: "We agreed on a date.",
    category: "verb",
    notes: "Commonly used with auf + accusative.",
  },
  {
    word: "ausleihen",
    article: null,
    plural: null,
    english: "to borrow; to lend",
    level: "A2",
    meaning: "To take something temporarily or to give it to someone temporarily, depending on the construction.",
    exampleDe: "Ich leihe mir ein Buch aus der Bibliothek aus.",
    exampleEn: "I'm borrowing a book from the library.",
    category: "verb",
    notes: "Separable: sich etwas ausleihen means to borrow; jemandem etwas ausleihen means to lend.",
  },
  {
    word: "umsteigen",
    article: null,
    plural: null,
    english: "to change trains or buses; to switch",
    level: "A2",
    meaning: "To leave one means of transport and continue with another, or more generally to switch to something different.",
    exampleDe: "In Hannover müssen wir umsteigen.",
    exampleEn: "We have to change trains in Hanover.",
    category: "verb",
    notes: "Separable verb: ich steige um; ich bin umgestiegen.",
  },
  {
    word: "sich lohnen",
    article: null,
    plural: null,
    english: "to be worthwhile; to pay off",
    level: "B1",
    meaning: "To be worth the time, effort, or money invested in something.",
    exampleDe: "Der frühe Besuch lohnt sich, weil es dann ruhiger ist.",
    exampleEn: "Visiting early is worthwhile because it is quieter then.",
    category: "verb",
    notes: "Often used impersonally: Es lohnt sich.",
  },
  {
    word: "verzichten",
    article: null,
    plural: null,
    english: "to do without; to forgo",
    level: "B1",
    meaning: "To consciously choose not to have, use, or do something.",
    exampleDe: "Ich versuche, unter der Woche auf Süßigkeiten zu verzichten.",
    exampleEn: "I try to go without sweets during the week.",
    category: "verb",
    notes: "Used with auf + accusative: auf etwas verzichten.",
  },
  {
    word: "zurechtkommen",
    article: null,
    plural: null,
    english: "to cope; to manage; to get along",
    level: "B2",
    meaning: "To manage a situation successfully or have a workable relationship with someone.",
    exampleDe: "Kommst du mit der neuen Software zurecht?",
    exampleEn: "Are you managing with the new software?",
    category: "verb",
    notes: "Separable and often used with mit + dative.",
  },
  {
    word: "vorbeikommen",
    article: null,
    plural: null,
    english: "to come by; to drop in",
    level: "A2–B1",
    meaning: "To visit someone briefly or pass by a particular place.",
    exampleDe: "Du kannst morgen gern auf einen Kaffee vorbeikommen.",
    exampleEn: "You're welcome to drop by for a coffee tomorrow.",
    category: "verb",
    notes: "Separable verb: ich komme vorbei; ich bin vorbeigekommen.",
  },
  {
    word: "wahrnehmen",
    article: null,
    plural: null,
    english: "to perceive; to attend; to take up",
    level: "B2",
    meaning: "To notice something with the senses or to make use of an appointment, opportunity, or responsibility.",
    exampleDe: "Leider kann ich den Termin morgen nicht wahrnehmen.",
    exampleEn: "Unfortunately, I can't attend the appointment tomorrow.",
    category: "verb",
    notes: "Separable verb: ich nehme wahr; ich habe wahrgenommen.",
  },

  // Slang
  {
    word: "Digga",
    article: null,
    plural: null,
    english: "mate; dude; bro",
    level: "B1",
    meaning: "A highly informal form of address, especially among younger speakers and in northern Germany.",
    exampleDe: "Digga, das glaubst du doch selbst nicht!",
    exampleEn: "Dude, you don't actually believe that!",
    category: "slang",
    notes: "Also written Digger. It does not literally refer to a person's body size.",
  },
  {
    word: "Alter!",
    article: null,
    plural: null,
    english: "dude!; man!; seriously!",
    level: "B1",
    meaning: "An informal form of address or exclamation expressing surprise, annoyance, or admiration.",
    exampleDe: "Alter, war das knapp!",
    exampleEn: "Man, that was close!",
    category: "slang",
    notes: "Tone matters greatly; it can sound friendly or confrontational.",
  },
  {
    word: "gönnen",
    article: null,
    plural: null,
    english: "to treat oneself; to be happy for someone",
    level: "B1",
    meaning: "In informal speech, to allow yourself something enjoyable or sincerely wish that another person enjoys their success.",
    exampleDe: "Nach der Prüfung gönne ich mir eine Pizza.",
    exampleEn: "After the exam, I'm treating myself to a pizza.",
    category: "slang",
    notes: "Gönn dir! means Treat yourself! or Go for it!",
  },
  {
    word: "verkacken",
    article: null,
    plural: null,
    english: "to screw up; to mess up",
    level: "B2",
    meaning: "A vulgar informal verb for failing at or badly mishandling something.",
    exampleDe: "Ich will die Prüfung nicht verkacken.",
    exampleEn: "I don't want to screw up the exam.",
    category: "slang",
    notes: "Vulgar. Neutral alternatives include vermasseln and falsch machen.",
  },
  {
    word: "verpeilt",
    article: null,
    plural: null,
    english: "scatterbrained; confused; disorganised",
    level: "B1",
    meaning: "Informally describes someone who is absent-minded, confused, or poorly organised.",
    exampleDe: "Heute Morgen war ich so verpeilt, dass ich meinen Schlüssel im Kühlschrank gesucht habe.",
    exampleEn: "I was so scatterbrained this morning that I looked for my key in the fridge.",
    category: "slang",
    notes: "Informal. Related to the verb verpeilen, meaning to miss, forget, or fail to understand something.",
  },
  {
    word: "abgehen",
    article: null,
    plural: null,
    english: "to be wild; to be happening; to go off",
    level: "B1–B2",
    meaning: "In slang, to describe an event, crowd, or person becoming very lively, energetic, or exciting.",
    exampleDe: "Auf dem Konzert ging es richtig ab.",
    exampleEn: "The concert was absolutely wild.",
    category: "slang",
    notes: "Separable verb: es geht ab; es ging ab. It has several non-slang meanings, so context matters.",
  },
  {
    word: "Ehrenmann",
    article: "der",
    plural: "Ehrenmänner",
    english: "legend; stand-up guy",
    level: "B1",
    meaning: "An approving slang term for a man who does something generous, loyal, or admirable.",
    exampleDe: "Du hast mir den letzten Platz freigehalten – Ehrenmann!",
    exampleEn: "You saved the last seat for me—what a legend!",
    category: "slang",
    notes: "Ehrenfrau is the corresponding feminine form.",
  },
  {
    word: "stabil",
    article: null,
    plural: null,
    english: "solid; impressive; really good",
    level: "B1",
    meaning: "Beyond its literal meaning of stable, slang uses it to praise something as strong, impressive, or dependable.",
    exampleDe: "Dein neues Fahrrad ist echt stabil.",
    exampleEn: "Your new bike is seriously impressive.",
    category: "slang",
    notes: "The slang meaning depends strongly on tone and context.",
  },
  {
    word: "mies",
    article: null,
    plural: null,
    english: "awful; nasty; extremely",
    level: "B1",
    meaning: "Informally describes something bad or unpleasant and can also intensify another adjective.",
    exampleDe: "Das Wetter ist heute richtig mies.",
    exampleEn: "The weather is really awful today.",
    category: "slang",
    notes: "In phrases such as mies gut, it can act as an intensifier.",
  },
  {
    word: "safe",
    article: null,
    plural: null,
    english: "definitely; certainly; for sure",
    level: "B1",
    meaning: "Youth slang used to express strong certainty or agreement.",
    exampleDe: "Bist du morgen dabei? – Safe!",
    exampleEn: "Are you joining us tomorrow? – Definitely!",
    category: "slang",
    notes: "An English borrowing whose German slang meaning is usually adverbial.",
  },

  // Distinctive and unusual German
  {
    word: "Kummerspeck",
    article: "der",
    plural: null,
    english: "weight gained from emotional eating",
    level: "C1",
    meaning: "Body fat gained through eating for comfort during sadness or emotional stress.",
    exampleDe: "Nach dem schwierigen Winter wollte er seinen Kummerspeck wieder loswerden.",
    exampleEn: "After the difficult winter, he wanted to lose the weight gained from comfort eating.",
    category: "unique",
    notes: "Literally: sorrow bacon.",
  },
  {
    word: "Treppenwitz",
    article: "der",
    plural: "Treppenwitze",
    english: "a comeback thought of too late",
    level: "C1",
    meaning: "A clever reply that only occurs to you after the conversation has ended; it can also describe an ironic historical absurdity.",
    exampleDe: "Die perfekte Antwort fiel mir erst auf dem Heimweg ein – ein klassischer Treppenwitz.",
    exampleEn: "The perfect reply only came to me on the way home—a classic staircase wit.",
    category: "unique",
    notes: "Related to the French expression esprit de l'escalier.",
  },
  {
    word: "Brückentag",
    article: "der",
    plural: "Brückentage",
    english: "bridge day between a public holiday and a weekend",
    level: "B2",
    meaning: "A working day taken off because it lies between a public holiday and a weekend.",
    exampleDe: "Viele nehmen den Freitag als Brückentag frei.",
    exampleEn: "Many people take Friday off to bridge the holiday and the weekend.",
    category: "unique",
    notes: "Literally: bridge day.",
  },
  {
    word: "Fingerspitzengefühl",
    article: "das",
    plural: null,
    english: "tact; sensitivity; instinctive finesse",
    level: "C1",
    meaning: "The ability to handle a delicate situation with intuition, tact, and sensitivity.",
    exampleDe: "Bei diesem Gespräch braucht man viel Fingerspitzengefühl.",
    exampleEn: "This conversation requires a great deal of tact.",
    category: "unique",
    notes: "Literally: fingertip feeling.",
  },
  {
    word: "Vorfreude",
    article: "die",
    plural: null,
    english: "joyful anticipation",
    level: "B2",
    meaning: "The pleasure and excitement felt while looking forward to a future event.",
    exampleDe: "Die Vorfreude auf die Reise ist fast so schön wie die Reise selbst.",
    exampleEn: "Looking forward to the trip is almost as enjoyable as the trip itself.",
    category: "unique",
    notes: "A concise noun for the happiness of anticipation.",
  },
  {
    word: "Waldeinsamkeit",
    article: "die",
    plural: null,
    english: "solitude in the forest",
    level: "C2",
    meaning: "A poetic sense of being alone and secluded in the woods.",
    exampleDe: "Der Dichter suchte Ruhe in der Waldeinsamkeit.",
    exampleEn: "The poet sought peace in the solitude of the forest.",
    category: "unique",
    notes: "Literary and uncommon in everyday conversation.",
  },
  {
    word: "Zugzwang",
    article: "der",
    plural: "Zugzwänge",
    english: "compulsion to act; zugzwang",
    level: "C1",
    meaning: "A situation in which someone is forced to act, especially a chess position where every possible move is disadvantageous.",
    exampleDe: "Durch die neue Frist geriet das Unternehmen unter Zugzwang.",
    exampleEn: "The new deadline forced the company to act.",
    category: "unique",
    notes: "Originally a chess term; also used figuratively.",
  },
  {
    word: "Erbsenzähler",
    article: "der",
    plural: "Erbsenzähler",
    english: "nitpicker; pedantic bean counter",
    level: "C1",
    meaning: "A person who pays excessive attention to tiny details or insists on exact accounting.",
    exampleDe: "Sei kein Erbsenzähler – ein Cent Unterschied ist doch egal.",
    exampleEn: "Don't be such a nitpicker—one cent's difference doesn't matter.",
    category: "unique",
    notes: "Literally: pea counter. The feminine form is Erbsenzählerin.",
  },
  {
    word: "Luftschloss",
    article: "das",
    plural: "Luftschlösser",
    english: "pipe dream; castle in the air",
    level: "B2",
    meaning: "An attractive plan or fantasy that is unrealistic and unlikely to become real.",
    exampleDe: "Ohne Finanzierung bleibt das Projekt ein Luftschloss.",
    exampleEn: "Without funding, the project will remain a pipe dream.",
    category: "unique",
    notes: "Literally: air castle.",
  },
  {
    word: "innerer Schweinehund",
    article: "der",
    plural: "inneren Schweinehunde",
    english: "inner resistance; lack of willpower",
    level: "C1",
    meaning: "The inner voice of laziness or reluctance that must be overcome to do something difficult or healthy.",
    exampleDe: "Heute habe ich meinen inneren Schweinehund überwunden und bin joggen gegangen.",
    exampleEn: "Today I overcame my inner resistance and went jogging.",
    category: "unique",
    notes: "Literally: inner pig-dog.",
  },

  // Colloquial German
  {
    word: "Kabelsalat",
    article: "der",
    plural: null,
    english: "tangle of cables",
    level: "B2",
    meaning: "A messy, confusing mass of intertwined cables.",
    exampleDe: "Hinter dem Schreibtisch herrscht völliger Kabelsalat.",
    exampleEn: "There is a complete tangle of cables behind the desk.",
    category: "colloquial",
    notes: "Literally: cable salad.",
  },
  {
    word: "Kaffeekasse",
    article: "die",
    plural: "Kaffeekassen",
    english: "shared coffee fund; office kitty",
    level: "B2",
    meaning: "A shared collection of small contributions used for coffee or minor communal expenses.",
    exampleDe: "Leg bitte zwei Euro in die Kaffeekasse.",
    exampleEn: "Please put two euros into the shared coffee fund.",
    category: "colloquial",
    notes: "Often found in workplaces, clubs, and shared spaces.",
  },
  {
    word: "Papiertiger",
    article: "der",
    plural: "Papiertiger",
    english: "paper tiger",
    level: "C1",
    meaning: "A person or institution that appears powerful or threatening but is actually ineffective.",
    exampleDe: "Ohne Kontrollen bleibt die neue Regel ein Papiertiger.",
    exampleEn: "Without enforcement, the new rule remains a paper tiger.",
    category: "colloquial",
    notes: "The image also exists in English.",
  },
  {
    word: "Warmduscher",
    article: "der",
    plural: "Warmduscher",
    english: "wimp; softy",
    level: "C1",
    meaning: "A teasing or mocking term for someone considered overly cautious, delicate, or comfort-loving.",
    exampleDe: "Lass dich nicht ärgern, wenn dich jemand Warmduscher nennt.",
    exampleEn: "Don't let it bother you if someone calls you a wimp.",
    category: "colloquial",
    notes: "Literally: warm showerer. Usually humorous, but it can be insulting.",
  },
  {
    word: "Extrawurst",
    article: "die",
    plural: "Extrawürste",
    english: "special treatment; special exception",
    level: "B2",
    meaning: "Preferential treatment or an exception made specifically for one person.",
    exampleDe: "Nur weil du zu spät bist, bekommst du keine Extrawurst.",
    exampleEn: "You don't get special treatment just because you're late.",
    category: "colloquial",
    notes: "Literally: extra sausage. Common in the phrase eine Extrawurst bekommen.",
  },
  {
    word: "Gedöns",
    article: "das",
    plural: null,
    english: "fuss; unnecessary stuff; palaver",
    level: "C1",
    meaning: "A dismissive colloquial word for unnecessary objects, activity, ceremony, or fuss.",
    exampleDe: "Mach nicht so viel Gedöns darum.",
    exampleEn: "Don't make such a fuss about it.",
    category: "colloquial",
    notes: "The exact translation depends heavily on context.",
  },
  {
    word: "Kuddelmuddel",
    article: "das",
    plural: null,
    english: "muddle; jumble; chaotic mess",
    level: "C1",
    meaning: "A confused, disorganized mixture or situation.",
    exampleDe: "Nach dem Umzug herrschte in der Wohnung ein großes Kuddelmuddel.",
    exampleEn: "After the move, the flat was a complete jumble.",
    category: "colloquial",
    notes: "Both das Kuddelmuddel and der Kuddelmuddel are accepted.",
  },
  {
    word: "Tohuwabohu",
    article: "das",
    plural: null,
    english: "commotion; complete chaos",
    level: "C1",
    meaning: "A state of noisy confusion, disorder, or chaos.",
    exampleDe: "Vor der Abfahrt herrschte im Flur ein einziges Tohuwabohu.",
    exampleEn: "Before departure, the hallway was complete chaos.",
    category: "colloquial",
    notes: "Ultimately derived from the Hebrew expression tohu wa-bohu.",
  },
  {
    word: "Pillepalle",
    article: null,
    plural: null,
    english: "trivial nonsense; a minor matter",
    level: "C1",
    meaning: "Something insignificant, easy, or not worth making a fuss about.",
    exampleDe: "Die kleine Reparatur ist doch Pillepalle.",
    exampleEn: "That small repair is no big deal.",
    category: "colloquial",
    notes: "Informal and often dismissive.",
  },
  {
    word: "Firlefanz",
    article: "der",
    plural: null,
    english: "nonsense; useless frills; unnecessary fuss",
    level: "C1",
    meaning: "Unnecessary decoration, meaningless activity, or trivial nonsense.",
    exampleDe: "Wir brauchen eine einfache Lösung ohne technischen Firlefanz.",
    exampleEn: "We need a simple solution without unnecessary technical frills.",
    category: "colloquial",
    notes: "Usually informal and mildly dismissive.",
  },

  // False friends
  {
    word: "Rat",
    article: "der",
    plural: "Räte",
    english: "advice; council",
    level: "A2",
    meaning: "Depending on context, helpful guidance or an official decision-making body.",
    exampleDe: "Kannst du mir einen Rat geben?",
    exampleEn: "Can you give me some advice?",
    category: "false_friend",
    notes: "False friend: the English animal rat is die Ratte. For pieces of advice, German commonly uses Ratschläge.",
  },
  {
    word: "Rezept",
    article: "das",
    plural: "Rezepte",
    english: "recipe; prescription",
    level: "A2",
    meaning: "Instructions for preparing food or a doctor's authorization for medicine.",
    exampleDe: "Für dieses Medikament brauche ich ein Rezept.",
    exampleEn: "I need a prescription for this medication.",
    category: "false_friend",
    notes: "False friend: English receipt usually translates as Quittung or Kassenbon.",
  },
  {
    word: "Mappe",
    article: "die",
    plural: "Mappen",
    english: "folder; portfolio",
    level: "A2",
    meaning: "A cover or case used to collect papers, drawings, or documents.",
    exampleDe: "Die Unterlagen liegen in der blauen Mappe.",
    exampleEn: "The documents are in the blue folder.",
    category: "false_friend",
    notes: "False friend: an English map is eine Karte or Landkarte.",
  },
  {
    word: "Mist",
    article: "der",
    plural: null,
    english: "manure; rubbish; damn",
    level: "A2–B1",
    meaning: "Literally animal manure; informally, rubbish or an exclamation of annoyance.",
    exampleDe: "Mist, ich habe meinen Schlüssel vergessen!",
    exampleEn: "Damn, I forgot my key!",
    category: "false_friend",
    notes: "False friend: English mist is der Nebel.",
  },
  {
    word: "kontrollieren",
    article: null,
    plural: null,
    english: "to check; to inspect; to monitor",
    level: "A2",
    meaning: "To examine whether something is correct, valid, safe, or functioning properly.",
    exampleDe: "Im Zug wird der Schaffner die Fahrkarten kontrollieren.",
    exampleEn: "The conductor will check the tickets on the train.",
    category: "false_friend",
    notes: "Often a false friend: English to control may instead mean steuern, regeln, or beherrschen.",
  },
  {
    word: "sich blamieren",
    article: null,
    plural: null,
    english: "to embarrass oneself",
    level: "B1",
    meaning: "To make yourself look foolish or cause yourself embarrassment.",
    exampleDe: "Ich wollte mich vor allen Leuten nicht blamieren.",
    exampleEn: "I didn't want to embarrass myself in front of everyone.",
    category: "false_friend",
    notes: "False friend: English to blame usually translates as jemandem die Schuld geben.",
  },
  {
    word: "irritiert",
    article: null,
    plural: null,
    english: "confused; unsettled; puzzled",
    level: "B1",
    meaning: "Describes someone who is uncertain or disturbed because something is unexpected or unclear.",
    exampleDe: "Sie war von seiner Antwort sichtlich irritiert.",
    exampleEn: "She was visibly puzzled by his answer.",
    category: "false_friend",
    notes: "English irritated more often means genervt or verärgert, although German irritiert can overlap in some contexts.",
  },
  {
    word: "prägnant",
    article: null,
    plural: null,
    english: "concise; striking; succinct",
    level: "C1",
    meaning: "Expressed clearly and memorably in few words or with a strongly defined effect.",
    exampleDe: "Bitte fasse das Ergebnis kurz und prägnant zusammen.",
    exampleEn: "Please summarize the result briefly and concisely.",
    category: "false_friend",
    notes: "False friend: English pregnant translates as schwanger.",
  },
  {
    word: "sympathisch",
    article: null,
    plural: null,
    english: "likeable; pleasant",
    level: "A2",
    meaning: "Having a pleasant personality or making a positive personal impression.",
    exampleDe: "Die neue Nachbarin wirkt sehr sympathisch.",
    exampleEn: "The new neighbour seems very likeable.",
    category: "false_friend",
    notes: "False friend: English sympathetic usually translates as mitfühlend or verständnisvoll.",
  },
  {
    word: "Billion",
    article: "die",
    plural: "Billionen",
    english: "trillion",
    level: "B2",
    meaning: "The number 1,000,000,000,000: one million million.",
    exampleDe: "Eine Billion hat zwölf Nullen.",
    exampleEn: "A trillion has twelve zeros.",
    category: "false_friend",
    notes: "False friend: English billion is die Milliarde in modern German.",
  },

  // Idioms
  {
    word: "nur Bahnhof verstehen",
    article: null,
    plural: null,
    english: "to not understand a word; to be completely lost",
    level: "B1",
    meaning: "To understand nothing at all about what is being explained or discussed.",
    exampleDe: "Bei der Erklärung der Steuerregeln verstehe ich nur Bahnhof.",
    exampleEn: "When the tax rules are explained, I don't understand a word.",
    category: "idiom",
    notes: "Literally: to understand only train station.",
  },
  {
    word: "nicht mein Bier sein",
    article: null,
    plural: null,
    english: "to be none of my business; not my problem",
    level: "B2",
    meaning: "To say that a matter does not concern you or is not your responsibility.",
    exampleDe: "Wie sie das organisiert, ist nicht mein Bier.",
    exampleEn: "How she organizes it is none of my business.",
    category: "idiom",
    notes: "Literally: not to be my beer.",
  },
  {
    word: "die Kirche im Dorf lassen",
    article: null,
    plural: null,
    english: "to keep things in perspective; not to go overboard",
    level: "B2",
    meaning: "To remain reasonable and avoid exaggerating a problem, demand, or reaction.",
    exampleDe: "Lass mal die Kirche im Dorf – so schlimm war der Fehler nicht.",
    exampleEn: "Let's keep things in perspective—the mistake wasn't that serious.",
    category: "idiom",
    notes: "Literally: to leave the church in the village.",
  },
  {
    word: "den Faden verlieren",
    article: null,
    plural: null,
    english: "to lose one's train of thought",
    level: "B1",
    meaning: "To forget what you were saying or lose track of an argument or story.",
    exampleDe: "Nach der Unterbrechung hatte ich völlig den Faden verloren.",
    exampleEn: "After the interruption, I completely lost my train of thought.",
    category: "idiom",
    notes: "Literally: to lose the thread.",
  },
  {
    word: "jemandem einen Bären aufbinden",
    article: null,
    plural: null,
    english: "to spin someone a tall tale; to fool someone",
    level: "C1",
    meaning: "To make someone believe an invented or deliberately misleading story.",
    exampleDe: "Willst du mir etwa einen Bären aufbinden?",
    exampleEn: "Are you trying to spin me a tall tale?",
    category: "idiom",
    notes: "Literally: to tie a bear onto someone.",
  },
  {
    word: "Schwein haben",
    article: null,
    plural: null,
    english: "to be lucky; to have a lucky escape",
    level: "B1",
    meaning: "To have unexpected good luck, especially when a situation could have ended badly.",
    exampleDe: "Da hast du noch einmal Schwein gehabt!",
    exampleEn: "You were lucky that time!",
    category: "idiom",
    notes: "Literally: to have a pig.",
  },
  {
    word: "aus einer Mücke einen Elefanten machen",
    article: null,
    plural: null,
    english: "to make a mountain out of a molehill",
    level: "B2",
    meaning: "To exaggerate a small problem until it appears much more serious than it is.",
    exampleDe: "Mach doch nicht aus jeder Mücke einen Elefanten.",
    exampleEn: "Don't make a mountain out of every molehill.",
    category: "idiom",
    notes: "Literally: to turn a mosquito into an elephant.",
  },
  {
    word: "jemandem auf der Nase herumtanzen",
    article: null,
    plural: null,
    english: "to walk all over someone",
    level: "C1",
    meaning: "To behave disrespectfully toward someone because they do not enforce boundaries or authority.",
    exampleDe: "Du darfst dir von den Kindern nicht auf der Nase herumtanzen lassen.",
    exampleEn: "You mustn't let the children walk all over you.",
    category: "idiom",
    notes: "Literally: to dance around on someone's nose.",
  },
  {
    word: "Butter bei die Fische",
    article: null,
    plural: null,
    english: "get to the point; let's get down to business",
    level: "C1",
    meaning: "A northern German expression demanding concrete facts, action, or a clear decision instead of more talk.",
    exampleDe: "Jetzt mal Butter bei die Fische: Wie viel kostet das wirklich?",
    exampleEn: "Let's get down to brass tacks: how much does it really cost?",
    category: "idiom",
    notes: "Literally: butter with the fish. The regional grammar is part of the fixed expression.",
  },
  {
    word: "mit der Tür ins Haus fallen",
    article: null,
    plural: null,
    english: "to come straight to the point too abruptly",
    level: "B2",
    meaning: "To raise a sensitive request or topic immediately and without a polite introduction.",
    exampleDe: "Ich will nicht mit der Tür ins Haus fallen, aber ich brauche deine Hilfe.",
    exampleEn: "I don't want to be too abrupt, but I need your help.",
    category: "idiom",
    notes: "Literally: to fall into the house with the door.",
  },
];
