import type { SeedWord } from "./types.js";

export const seedWords: SeedWord[] = [
  {
    word: "Feierabend",
    article: "der",
    plural: "Feierabende",
    english: "end of the working day; time after work",
    level: "A2–B1",
    meaning: "The time after you have finished work for the day. It is also used when announcing that you are stopping work.",
    exampleDe: "Ich mache jetzt Feierabend.",
    exampleEn: "I'm finishing work for the day now.",
    category: "everyday",
    notes: "There is no perfect one-word English equivalent. Related: das Feierabendbier.",
  },
  {
    word: "Kopfkino",
    article: "das",
    plural: null,
    english: "vivid imagination; mental cinema",
    level: "B2",
    meaning: "A vivid sequence of imagined scenes playing out in your head.",
    exampleDe: "Nach seiner Geschichte hatte ich sofort Kopfkino.",
    exampleEn: "After his story, I could immediately picture the whole thing.",
    category: "unique",
    notes: "Literally: head cinema.",
  },
  {
    word: "jein",
    article: null,
    plural: null,
    english: "yes and no; kind of",
    level: "B1",
    meaning: "An informal blend of ja and nein, used when the honest answer is partly yes and partly no.",
    exampleDe: "Kommst du morgen? – Jein, vielleicht erst später.",
    exampleEn: "Are you coming tomorrow? – Yes and no, maybe only later.",
    category: "slang",
    notes: "A blend of ja + nein.",
  },
  {
    word: "auf dem Schlauch stehen",
    article: null,
    plural: null,
    english: "to be slow on the uptake; to draw a blank",
    level: "B2",
    meaning: "To be temporarily unable to understand or remember something obvious.",
    exampleDe: "Ich stehe gerade völlig auf dem Schlauch.",
    exampleEn: "I'm drawing a complete blank right now.",
    category: "idiom",
    notes: "Literally: to stand on the hose.",
  },
  {
    word: "erledigen",
    article: null,
    plural: null,
    english: "to take care of; to complete",
    level: "A2",
    meaning: "To complete a task, errand, or piece of work.",
    exampleDe: "Ich muss heute noch ein paar Dinge erledigen.",
    exampleEn: "I still have to take care of a few things today.",
    category: "verb",
    notes: null,
  },
  {
    word: "völlig Banane",
    article: null,
    plural: null,
    english: "completely absurd; ridiculous",
    level: "B2",
    meaning: "An informal way to say that something makes no sense or is ridiculous.",
    exampleDe: "Diese Regel ist doch völlig Banane.",
    exampleEn: "This rule is completely ridiculous.",
    category: "colloquial",
    notes: "Informal. Banane normally means banana.",
  },
  {
    word: "bekommen",
    article: null,
    plural: null,
    english: "to get; to receive",
    level: "A1",
    meaning: "To receive or get something. It does not normally mean “to become.”",
    exampleDe: "Ich habe gestern eine Nachricht bekommen.",
    exampleEn: "I received a message yesterday.",
    category: "false_friend",
    notes: "False friend: English become usually translates as werden.",
  },
  {
    word: "doch",
    article: null,
    plural: null,
    english: "on the contrary; after all; indeed",
    level: "B1",
    meaning: "A versatile particle often used to contradict a negative statement or add emphasis.",
    exampleDe: "Du kommst nicht? – Doch, ich komme!",
    exampleEn: "You're not coming? – Yes, I am!",
    category: "everyday",
    notes: "Its translation depends heavily on context.",
  },
  {
    word: "verschlimmbessern",
    article: null,
    plural: null,
    english: "to make something worse while trying to improve it",
    level: "C1",
    meaning: "To attempt an improvement but produce a worse result.",
    exampleDe: "Mit dem Update wurde die App eher verschlimmbessert.",
    exampleEn: "The update made the app worse rather than improving it.",
    category: "unique",
    notes: "A blend of verschlimmern and verbessern.",
  },
  {
    word: "abhängen",
    article: null,
    plural: null,
    english: "to depend; to hang out",
    level: "B1",
    meaning: "Depending on context, it can mean that something depends on something else or that people relax together.",
    exampleDe: "Das hängt vom Wetter ab.",
    exampleEn: "That depends on the weather.",
    category: "verb",
    notes: "Separable verb: es hängt ... ab.",
  },
  {
    word: "Bock haben",
    article: null,
    plural: null,
    english: "to feel like doing something",
    level: "B1",
    meaning: "A very common informal expression for wanting or feeling motivated to do something.",
    exampleDe: "Hast du Bock auf einen Spaziergang?",
    exampleEn: "Do you feel like going for a walk?",
    category: "slang",
    notes: "Informal. Often used with auf + accusative.",
  },
  {
    word: "Pi mal Daumen",
    article: null,
    plural: null,
    english: "roughly; approximately",
    level: "B2",
    meaning: "An informal way to indicate a rough estimate rather than an exact calculation.",
    exampleDe: "Das sind Pi mal Daumen zwanzig Kilometer.",
    exampleEn: "That's roughly twenty kilometres.",
    category: "idiom",
    notes: "Literally: pi times thumb.",
  },
  {
    word: "Handy",
    article: "das",
    plural: "Handys",
    english: "mobile phone; cell phone",
    level: "A1",
    meaning: "The everyday German word for a mobile phone, despite looking like an English adjective.",
    exampleDe: "Mein Handy ist fast leer.",
    exampleEn: "My phone is almost out of battery.",
    category: "false_friend",
    notes: "In English, handy means useful or convenient.",
  },
  {
    word: "Schnapsidee",
    article: "die",
    plural: "Schnapsideen",
    english: "crazy or foolish idea",
    level: "B2",
    meaning: "A poorly thought-out, unrealistic, or ridiculous idea.",
    exampleDe: "Bei dem Wetter zu zelten war eine Schnapsidee.",
    exampleEn: "Camping in that weather was a foolish idea.",
    category: "colloquial",
    notes: "Literally: liquor idea.",
  },
];
