import type { SeedWord } from "./types.js";

export const seedWords: SeedWord[] = [
  {
    word: "Feierabend",
    article: "der",
    plural: "Feierabende",
    english: "end of the working day; time after work",
    level: "A2–B1",
    meaning: "The time after you have finished work for the day. It is also used when announcing that you are stopping work.",
    exampleDe: "Ich mache jetzt Feierabend.",
    exampleEn: "I'm finishing work for the day now.",
    category: "everyday",
    notes: "There is no perfect one-word English equivalent. Related: das Feierabendbier.",
  },
  {
    word: "Kopfkino",
    article: "das",
    plural: null,
    english: "vivid imagination; mental cinema",
    level: "B2",
    meaning: "A vivid sequence of imagined scenes playing out in your head.",
    exampleDe: "Nach seiner Geschichte hatte ich sofort Kopfkino.",
    exampleEn: "After his story, I could immediately picture the whole thing.",
    category: "unique",
    notes: "Literally: head cinema.",
  },
  {
    word: "jein",
    article: null,
    plural: null,
    english: "yes and no; kind of",
    level: "B1",
    meaning: "An informal blend of ja and nein, used when the honest answer is partly yes and partly no.",
    exampleDe: "Kommst du morgen? – Jein, vielleicht erst später.",
    exampleEn: "Are you coming tomorrow? – Yes and no, maybe only later.",
    category: "slang",
    notes: "A blend of ja + nein.",
  },
  {
    word: "auf dem Schlauch stehen",
    article: null,
    plural: null,
    english: "to be slow on the uptake; to draw a blank",
    level: "B2",
    meaning: "To be temporarily unable to understand or remember something obvious.",
    exampleDe: "Ich stehe gerade völlig auf dem Schlauch.",
    exampleEn: "I'm drawing a complete blank right now.",
    category: "idiom",
    notes: "Literally: to stand on the hose.",
  },
  {
    word: "erledigen",
    article: null,
    plural: null,
    english: "to take care of; to complete",
    level: "A2",
    meaning: "To complete a task, errand, or piece of work.",
    exampleDe: "Ich muss heute noch ein paar Dinge erledigen.",
    exampleEn: "I still have to take care of a few things today.",
    category: "verb",
    notes: null,
  },
  {
    word: "völlig Banane",
    article: null,
    plural: null,
    english: "completely absurd; ridiculous",
    level: "B2",
    meaning: "An informal way to say that something makes no sense or is ridiculous.",
    exampleDe: "Diese Regel ist doch völlig Banane.",
    exampleEn: "This rule is completely ridiculous.",
    category: "colloquial",
    notes: "Informal. Banane normally means banana.",
  },
  {
    word: "bekommen",
    article: null,
    plural: null,
    english: "to get; to receive",
    level: "A1",
    meaning: "To receive or get something. It does not normally mean “to become.”",
    exampleDe: "Ich habe gestern eine Nachricht bekommen.",
    exampleEn: "I received a message yesterday.",
    category: "false_friend",
    notes: "False friend: English become usually translates as werden.",
  },
  {
    word: "doch",
    article: null,
    plural: null,
    english: "on the contrary; after all; indeed",
    level: "B1",
    meaning: "A versatile particle often used to contradict a negative statement or add emphasis.",
    exampleDe: "Du kommst nicht? – Doch, ich komme!",
    exampleEn: "You're not coming? – Yes, I am!",
    category: "everyday",
    notes: "Its translation depends heavily on context.",
  },
  {
    word: "verschlimmbessern",
    article: null,
    plural: null,
    english: "to make something worse while trying to improve it",
    level: "C1",
    meaning: "To attempt an improvement but produce a worse result.",
    exampleDe: "Mit dem Update wurde die App eher verschlimmbessert.",
    exampleEn: "The update made the app worse rather than improving it.",
    category: "unique",
    notes: "A blend of verschlimmern and verbessern.",
  },
  {
    word: "abhängen",
    article: null,
    plural: null,
    english: "to depend; to hang out",
    level: "B1",
    meaning: "Depending on context, it can mean that something depends on something else or that people relax together.",
    exampleDe: "Das hängt vom Wetter ab.",
    exampleEn: "That depends on the weather.",
    category: "verb",
    notes: "Separable verb: es hängt ... ab.",
  },
  {
    word: "Bock haben",
    article: null,
    plural: null,
    english: "to feel like doing something",
    level: "B1",
    meaning: "A very common informal expression for wanting or feeling motivated to do something.",
    exampleDe: "Hast du Bock auf einen Spaziergang?",
    exampleEn: "Do you feel like going for a walk?",
    category: "slang",
    notes: "Informal. Often used with auf + accusative.",
  },
  {
    word: "Pi mal Daumen",
    article: null,
    plural: null,
    english: "roughly; approximately",
    level: "B2",
    meaning: "An informal way to indicate a rough estimate rather than an exact calculation.",
    exampleDe: "Das sind Pi mal Daumen zwanzig Kilometer.",
    exampleEn: "That's roughly twenty kilometres.",
    category: "idiom",
    notes: "Literally: pi times thumb.",
  },
  {
    word: "Handy",
    article: "das",
    plural: "Handys",
    english: "mobile phone; cell phone",
    level: "A1",
    meaning: "The everyday German word for a mobile phone, despite looking like an English adjective.",
    exampleDe: "Mein Handy ist fast leer.",
    exampleEn: "My phone is almost out of battery.",
    category: "false_friend",
    notes: "In English, handy means useful or convenient.",
  },
  {
    word: "Schnapsidee",
    article: "die",
    plural: "Schnapsideen",
    english: "crazy or foolish idea",
    level: "B2",
    meaning: "A poorly thought-out, unrealistic, or ridiculous idea.",
    exampleDe: "Bei dem Wetter zu zelten war eine Schnapsidee.",
    exampleEn: "Camping in that weather was a foolish idea.",
    category: "colloquial",
    notes: "Literally: liquor idea.",
  },
  {
    word: "Alltag",
    article: "der",
    plural: "Alltage",
    english: "everyday life; daily routine",
    level: "A2",
    meaning: "The ordinary activities and routines that make up daily life.",
    exampleDe: "Nach dem Urlaub beginnt wieder der Alltag.",
    exampleEn: "After the holiday, everyday life begins again.",
    category: "everyday",
    notes: "Related adjective: alltäglich – everyday or ordinary.",
  },
  {
    word: "Mahlzeit",
    article: "die",
    plural: "Mahlzeiten",
    english: "meal",
    level: "A1",
    meaning: "Food eaten at a particular time, such as breakfast, lunch, or dinner.",
    exampleDe: "Das Frühstück ist meine liebste Mahlzeit.",
    exampleEn: "Breakfast is my favourite meal.",
    category: "everyday",
    notes: "Mahlzeit! is also an informal lunchtime greeting, especially at work.",
  },
  {
    word: "Termin",
    article: "der",
    plural: "Termine",
    english: "appointment; scheduled date",
    level: "A1–A2",
    meaning: "An arranged appointment or a fixed date for an event.",
    exampleDe: "Ich habe morgen einen Termin beim Zahnarzt.",
    exampleEn: "I have a dentist's appointment tomorrow.",
    category: "everyday",
    notes: "Use einen Termin vereinbaren for arranging an appointment.",
  },
  {
    word: "Schlange",
    article: "die",
    plural: "Schlangen",
    english: "queue; snake",
    level: "A2",
    meaning: "Depending on context, either a line of waiting people or a snake.",
    exampleDe: "An der Kasse steht eine lange Schlange.",
    exampleEn: "There is a long queue at the checkout.",
    category: "everyday",
    notes: "Schlange stehen means to queue or wait in line.",
  },
  {
    word: "Umweg",
    article: "der",
    plural: "Umwege",
    english: "detour; roundabout route",
    level: "B1",
    meaning: "A route that is longer than the direct way to a destination.",
    exampleDe: "Wegen der Baustelle müssen wir einen Umweg fahren.",
    exampleEn: "Because of the roadworks, we have to take a detour.",
    category: "everyday",
    notes: "Also used figuratively for an indirect way of achieving something.",
  },
  {
    word: "Quittung",
    article: "die",
    plural: "Quittungen",
    english: "receipt",
    level: "A2",
    meaning: "A written confirmation that money has been paid or something has been received.",
    exampleDe: "Brauchen Sie die Quittung?",
    exampleEn: "Do you need the receipt?",
    category: "everyday",
    notes: "A Kassenbon is specifically the printed receipt from a till.",
  },
  {
    word: "Kassenbon",
    article: "der",
    plural: "Kassenbons",
    english: "till receipt; sales receipt",
    level: "A2",
    meaning: "The printed receipt produced by a shop's checkout.",
    exampleDe: "Bewahren Sie den Kassenbon für die Rückgabe auf.",
    exampleEn: "Keep the receipt in case you return the item.",
    category: "everyday",
    notes: "Often shortened to Bon in everyday speech.",
  },
  {
    word: "Verspätung",
    article: "die",
    plural: "Verspätungen",
    english: "delay; lateness",
    level: "A2",
    meaning: "The state of arriving or happening later than planned.",
    exampleDe: "Der Zug hat zwanzig Minuten Verspätung.",
    exampleEn: "The train is twenty minutes late.",
    category: "everyday",
    notes: "The standard travel phrase is Verspätung haben.",
  },
  {
    word: "sich verabreden",
    article: null,
    plural: null,
    english: "to arrange to meet",
    level: "A2",
    meaning: "To make plans with another person to meet at a particular time or place.",
    exampleDe: "Wir haben uns für Samstag verabredet.",
    exampleEn: "We arranged to meet on Saturday.",
    category: "verb",
    notes: "Reflexive and separable: wir verabreden uns; wir haben uns verabredet.",
  },
  {
    word: "nachholen",
    article: null,
    plural: null,
    english: "to catch up on; to make up for",
    level: "B1",
    meaning: "To do something later that could not be done at the intended time.",
    exampleDe: "Wir holen das Treffen nächste Woche nach.",
    exampleEn: "We'll make up for the meeting next week.",
    category: "verb",
    notes: "Separable verb: ich hole nach; ich habe nachgeholt.",
  },
  {
    word: "sich gewöhnen an",
    article: null,
    plural: null,
    english: "to get used to",
    level: "B1",
    meaning: "To become familiar or comfortable with a new situation through experience.",
    exampleDe: "Ich muss mich noch an das Wetter gewöhnen.",
    exampleEn: "I still have to get used to the weather.",
    category: "verb",
    notes: "Used with an + accusative: sich an etwas gewöhnen.",
  },
  {
    word: "überlegen",
    article: null,
    plural: null,
    english: "to consider; to think about",
    level: "A2",
    meaning: "To think carefully before making a decision or giving an answer.",
    exampleDe: "Ich muss mir das noch überlegen.",
    exampleEn: "I still need to think that over.",
    category: "verb",
    notes: "Do not confuse the verb überlegen with the adjective überlegen – superior.",
  },
  {
    word: "auffallen",
    article: null,
    plural: null,
    english: "to stand out; to be noticed",
    level: "B1",
    meaning: "To attract attention or become noticeable because something is unusual.",
    exampleDe: "Mir ist sofort sein Akzent aufgefallen.",
    exampleEn: "I noticed his accent immediately.",
    category: "verb",
    notes: "The person noticing is in the dative: Mir fällt etwas auf.",
  },
  {
    word: "mitbringen",
    article: null,
    plural: null,
    english: "to bring along",
    level: "A1",
    meaning: "To bring a person or thing with you when you go somewhere.",
    exampleDe: "Soll ich etwas zum Essen mitbringen?",
    exampleEn: "Should I bring something to eat?",
    category: "verb",
    notes: "Separable verb: ich bringe mit; ich habe mitgebracht.",
  },
  {
    word: "stattfinden",
    article: null,
    plural: null,
    english: "to take place",
    level: "A2",
    meaning: "To happen at an arranged time and place.",
    exampleDe: "Das Konzert findet draußen statt.",
    exampleEn: "The concert takes place outside.",
    category: "verb",
    notes: "Separable verb: es findet statt; es hat stattgefunden.",
  },
  {
    word: "ausreichen",
    article: null,
    plural: null,
    english: "to be sufficient; to be enough",
    level: "B1",
    meaning: "To be enough for a particular need or purpose.",
    exampleDe: "Das Geld reicht für die Fahrkarte aus.",
    exampleEn: "The money is enough for the ticket.",
    category: "verb",
    notes: "Separable verb: es reicht aus; es hat ausgereicht.",
  },
  {
    word: "krass",
    article: null,
    plural: null,
    english: "intense; extreme; awesome",
    level: "B1",
    meaning: "A very common informal adjective expressing that something is extreme, surprising, or impressive.",
    exampleDe: "Krass, damit habe ich nicht gerechnet!",
    exampleEn: "Wow, I didn't expect that!",
    category: "slang",
    notes: "Its tone can be positive or negative depending on context.",
  },
  {
    word: "quatschen",
    article: null,
    plural: null,
    english: "to chat; to talk nonsense",
    level: "B1",
    meaning: "Informally, to chat casually; in another context, to say something nonsensical.",
    exampleDe: "Wir haben den ganzen Abend gequatscht.",
    exampleEn: "We chatted all evening.",
    category: "slang",
    notes: "Quatsch! means Nonsense!",
  },
  {
    word: "chillen",
    article: null,
    plural: null,
    english: "to chill; to relax",
    level: "A2–B1",
    meaning: "An informal borrowed verb meaning to relax or spend time without doing much.",
    exampleDe: "Wir chillen heute einfach zu Hause.",
    exampleEn: "We're just chilling at home today.",
    category: "slang",
    notes: "Common among younger speakers; past participle: gechillt.",
  },
  {
    word: "Kohle",
    article: "die",
    plural: null,
    english: "money; cash",
    level: "B1",
    meaning: "Informal slang for money. Its literal meaning is coal.",
    exampleDe: "Dafür habe ich gerade keine Kohle.",
    exampleEn: "I don't have the cash for that right now.",
    category: "slang",
    notes: "Informal. In its literal sense, Kohle means coal.",
  },
  {
    word: "Kumpel",
    article: "der",
    plural: "Kumpel",
    english: "mate; buddy",
    level: "A2",
    meaning: "An informal word for a male friend or companion.",
    exampleDe: "Ich gehe mit ein paar Kumpeln ins Kino.",
    exampleEn: "I'm going to the cinema with a few mates.",
    category: "slang",
    notes: "Originally also referred to a miner.",
  },
  {
    word: "Moin",
    article: null,
    plural: null,
    english: "hello; hi",
    level: "A1",
    meaning: "A greeting strongly associated with northern Germany and usable throughout the day.",
    exampleDe: "Moin! Wie geht's dir?",
    exampleEn: "Hi! How are you?",
    category: "slang",
    notes: "Despite the similarity to Morgen, it is not restricted to the morning.",
  },
  {
    word: "labern",
    article: null,
    plural: null,
    english: "to ramble; to yap",
    level: "B2",
    meaning: "To talk at length in an annoying, trivial, or nonsensical way.",
    exampleDe: "Hör auf zu labern und komm zur Sache.",
    exampleEn: "Stop rambling and get to the point.",
    category: "slang",
    notes: "Informal and sometimes dismissive.",
  },
  {
    word: "zocken",
    article: null,
    plural: null,
    english: "to play video games; to gamble",
    level: "B1",
    meaning: "Informally, to play video games; it can also mean to gamble.",
    exampleDe: "Wir zocken am Wochenende zusammen.",
    exampleEn: "We play video games together at the weekend.",
    category: "slang",
    notes: "The intended meaning usually follows from context.",
  },
  {
    word: "Fernweh",
    article: "das",
    plural: null,
    english: "longing to travel; wanderlust",
    level: "B2",
    meaning: "A strong longing for distant places and the desire to travel away from home.",
    exampleDe: "Wenn ich die Bilder sehe, bekomme ich sofort Fernweh.",
    exampleEn: "When I see the pictures, I immediately long to travel.",
    category: "unique",
    notes: "Often described as the opposite of Heimweh – homesickness.",
  },
  {
    word: "Fremdschämen",
    article: "das",
    plural: null,
    english: "second-hand embarrassment",
    level: "C1",
    meaning: "The embarrassment you feel because of another person's awkward or inappropriate behaviour.",
    exampleDe: "Bei dieser Szene musste ich mich richtig fremdschämen.",
    exampleEn: "That scene gave me serious second-hand embarrassment.",
    category: "unique",
    notes: "Related verb: sich fremdschämen.",
  },
  {
    word: "Geborgenheit",
    article: "die",
    plural: null,
    english: "sense of safety and belonging",
    level: "C1",
    meaning: "A warm feeling of being safe, protected, accepted, and at home.",
    exampleDe: "Bei ihrer Familie findet sie Ruhe und Geborgenheit.",
    exampleEn: "With her family, she finds peace and a sense of security.",
    category: "unique",
    notes: "English usually needs a phrase rather than one exact equivalent.",
  },
  {
    word: "Schadenfreude",
    article: "die",
    plural: null,
    english: "pleasure at another person's misfortune",
    level: "B2",
    meaning: "The feeling of satisfaction or amusement caused by someone else's bad luck.",
    exampleDe: "Ein bisschen Schadenfreude konnte er sich nicht verkneifen.",
    exampleEn: "He couldn't suppress a little pleasure at their misfortune.",
    category: "unique",
    notes: "The German word is also used as a loanword in English.",
  },
  {
    word: "Torschlusspanik",
    article: "die",
    plural: null,
    english: "fear of running out of time",
    level: "C1",
    meaning: "Anxiety that important life opportunities are disappearing as time passes.",
    exampleDe: "Aus Torschlusspanik sollte man keine große Entscheidung treffen.",
    exampleEn: "You shouldn't make a major decision out of fear that time is running out.",
    category: "unique",
    notes: "Literally: gate-closing panic.",
  },
  {
    word: "Weltschmerz",
    article: "der",
    plural: null,
    english: "world-weariness; melancholy about the world",
    level: "C1",
    meaning: "A deep sadness caused by the gap between how the world is and how one wishes it were.",
    exampleDe: "Der Roman ist voller Sehnsucht und Weltschmerz.",
    exampleEn: "The novel is full of longing and world-weariness.",
    category: "unique",
    notes: "Literally: world pain.",
  },
  {
    word: "Zeitgeist",
    article: "der",
    plural: null,
    english: "spirit of the age; zeitgeist",
    level: "C1",
    meaning: "The dominant ideas, attitudes, and cultural mood of a particular period.",
    exampleDe: "Der Film trifft den Zeitgeist der neunziger Jahre.",
    exampleEn: "The film captures the spirit of the 1990s.",
    category: "unique",
    notes: "Also used as a German loanword in English.",
  },
  {
    word: "Erklärungsnot",
    article: "die",
    plural: null,
    english: "difficulty explaining or justifying oneself",
    level: "C1",
    meaning: "A situation in which someone struggles to give a convincing explanation or justification.",
    exampleDe: "Nach den widersprüchlichen Aussagen geriet er in Erklärungsnot.",
    exampleEn: "After the contradictory statements, he struggled to explain himself.",
    category: "unique",
    notes: "Common phrase: in Erklärungsnot geraten.",
  },
  {
    word: "na ja",
    article: null,
    plural: null,
    english: "well; so-so; not really",
    level: "A2",
    meaning: "A conversational response expressing hesitation, mild disagreement, or a lack of enthusiasm.",
    exampleDe: "War der Film gut? – Na ja, es ging.",
    exampleEn: "Was the film good? – Well, it was okay.",
    category: "colloquial",
    notes: "The exact meaning depends strongly on tone.",
  },
  {
    word: "alles klar",
    article: null,
    plural: null,
    english: "all right; understood; everything okay",
    level: "A1",
    meaning: "A common expression used to confirm understanding or ask whether everything is okay.",
    exampleDe: "Wir treffen uns um acht. – Alles klar!",
    exampleEn: "We'll meet at eight. – All right!",
    category: "colloquial",
    notes: "Alles klar? can mean Is everything okay? or Got it?",
  },
  {
    word: "kein Ding",
    article: null,
    plural: null,
    english: "no problem; no big deal",
    level: "A2",
    meaning: "An informal response saying that something is not a problem or inconvenience.",
    exampleDe: "Danke für deine Hilfe! – Kein Ding!",
    exampleEn: "Thanks for your help! – No problem!",
    category: "colloquial",
    notes: "Informal alternative to kein Problem.",
  },
  {
    word: "fix und fertig",
    article: null,
    plural: null,
    english: "completely exhausted",
    level: "B1",
    meaning: "An informal expression for being physically or emotionally worn out.",
    exampleDe: "Nach der langen Wanderung war ich fix und fertig.",
    exampleEn: "After the long hike, I was completely exhausted.",
    category: "colloquial",
    notes: "Depending on context, fertig can mean finished, ready, or exhausted.",
  },
  {
    word: "auf jeden Fall",
    article: null,
    plural: null,
    english: "definitely; in any case",
    level: "A2",
    meaning: "A frequent expression used to emphasize certainty or say that something applies regardless.",
    exampleDe: "Da möchte ich auf jeden Fall hin.",
    exampleEn: "I definitely want to go there.",
    category: "colloquial",
    notes: "Often shortened informally to auf jeden.",
  },
  {
    word: "mal sehen",
    article: null,
    plural: null,
    english: "we'll see; let's see",
    level: "A2",
    meaning: "A casual way to postpone a decision or express uncertainty about what will happen.",
    exampleDe: "Kommst du morgen mit? – Mal sehen.",
    exampleEn: "Are you coming along tomorrow? – We'll see.",
    category: "colloquial",
    notes: "Mal is an unstressed conversational form related to einmal.",
  },
  {
    word: "Bescheid sagen",
    article: null,
    plural: null,
    english: "to let someone know",
    level: "A2",
    meaning: "A very common expression meaning to inform someone about a decision or situation.",
    exampleDe: "Sag mir bitte Bescheid, wenn du angekommen bist.",
    exampleEn: "Please let me know when you've arrived.",
    category: "colloquial",
    notes: "Bescheid is capitalized because it is a noun.",
  },
  {
    word: "passt schon",
    article: null,
    plural: null,
    english: "it's fine; that'll do",
    level: "B1",
    meaning: "An informal expression saying that something is acceptable or does not need changing.",
    exampleDe: "Soll ich das noch ändern? – Nein, passt schon.",
    exampleEn: "Should I change that? – No, it's fine.",
    category: "colloquial",
    notes: "Depending on tone, it can sound reassuring or slightly dismissive.",
  },
  {
    word: "aktuell",
    article: null,
    plural: null,
    english: "current; currently",
    level: "A2",
    meaning: "Relating to the present time or the latest available information.",
    exampleDe: "Wie ist die aktuelle Lage?",
    exampleEn: "What is the current situation?",
    category: "false_friend",
    notes: "False friend: English actual usually means tatsächlich or wirklich.",
  },
  {
    word: "eventuell",
    article: null,
    plural: null,
    english: "possibly; perhaps",
    level: "B1",
    meaning: "Used when something might happen or be true, but is not certain.",
    exampleDe: "Ich komme eventuell etwas später.",
    exampleEn: "I might arrive a little later.",
    category: "false_friend",
    notes: "False friend: English eventually usually translates as schließlich or letztendlich.",
  },
  {
    word: "Chef",
    article: "der",
    plural: "Chefs",
    english: "boss; manager",
    level: "A1",
    meaning: "The person in charge of a workplace, team, or organization.",
    exampleDe: "Mein Chef ist diese Woche im Urlaub.",
    exampleEn: "My boss is on holiday this week.",
    category: "false_friend",
    notes: "False friend: a professional cook is usually a Koch or Küchenchef.",
  },
  {
    word: "Gift",
    article: "das",
    plural: "Gifte",
    english: "poison",
    level: "A2",
    meaning: "A substance that can cause illness, injury, or death when absorbed by an organism.",
    exampleDe: "Diese Pflanze enthält ein starkes Gift.",
    exampleEn: "This plant contains a powerful poison.",
    category: "false_friend",
    notes: "False friend: English gift translates as Geschenk.",
  },
  {
    word: "brav",
    article: null,
    plural: null,
    english: "well-behaved; obedient",
    level: "A2",
    meaning: "Behaving properly and doing what is expected, especially of children or animals.",
    exampleDe: "Der Hund wartet ganz brav vor der Tür.",
    exampleEn: "The dog is waiting very obediently outside the door.",
    category: "false_friend",
    notes: "False friend: English brave translates as mutig.",
  },
  {
    word: "sensibel",
    article: null,
    plural: null,
    english: "sensitive",
    level: "B1",
    meaning: "Easily affected emotionally or requiring careful handling.",
    exampleDe: "Das ist ein sensibles Thema.",
    exampleEn: "That is a sensitive subject.",
    category: "false_friend",
    notes: "False friend: English sensible usually translates as vernünftig.",
  },
  {
    word: "also",
    article: null,
    plural: null,
    english: "so; therefore; well then",
    level: "A1",
    meaning: "A linking or conversational word used to introduce a conclusion, consequence, or new step.",
    exampleDe: "Also, fangen wir an!",
    exampleEn: "So, let's get started!",
    category: "false_friend",
    notes: "False friend: English also usually translates as auch.",
  },
  {
    word: "Gymnasium",
    article: "das",
    plural: "Gymnasien",
    english: "academic secondary school",
    level: "A2",
    meaning: "A type of secondary school that typically prepares pupils for the Abitur and university study.",
    exampleDe: "Nach der Grundschule wechselte sie aufs Gymnasium.",
    exampleEn: "After primary school, she moved to an academic secondary school.",
    category: "false_friend",
    notes: "False friend: an English gym is a Fitnessstudio or Sporthalle.",
  },
  {
    word: "jemandem die Daumen drücken",
    article: null,
    plural: null,
    english: "to keep one's fingers crossed for someone",
    level: "B1",
    meaning: "To wish someone good luck or hope that they succeed.",
    exampleDe: "Ich drücke dir für die Prüfung die Daumen.",
    exampleEn: "I'm keeping my fingers crossed for your exam.",
    category: "idiom",
    notes: "German presses thumbs where English crosses fingers.",
  },
  {
    word: "Tomaten auf den Augen haben",
    article: null,
    plural: null,
    english: "to fail to notice the obvious",
    level: "B1",
    meaning: "To overlook something that is directly in front of you or should be easy to see.",
    exampleDe: "Die Schlüssel liegen doch da – hast du Tomaten auf den Augen?",
    exampleEn: "The keys are right there—are you blind to the obvious?",
    category: "idiom",
    notes: "Literally: to have tomatoes on one's eyes.",
  },
  {
    word: "ins Fettnäpfchen treten",
    article: null,
    plural: null,
    english: "to put one's foot in it",
    level: "B2",
    meaning: "To say or do something tactless that causes embarrassment.",
    exampleDe: "Mit seiner Frage ist er voll ins Fettnäpfchen getreten.",
    exampleEn: "He really put his foot in it with that question.",
    category: "idiom",
    notes: "Literally: to step into the little bowl of fat.",
  },
  {
    word: "zwei Fliegen mit einer Klappe schlagen",
    article: null,
    plural: null,
    english: "to kill two birds with one stone",
    level: "B2",
    meaning: "To accomplish two goals with a single action.",
    exampleDe: "Mit dem Fahrrad spare ich Geld und mache Sport – zwei Fliegen mit einer Klappe.",
    exampleEn: "By cycling I save money and exercise—two birds with one stone.",
    category: "idiom",
    notes: "Literally: to hit two flies with one swatter.",
  },
  {
    word: "den Nagel auf den Kopf treffen",
    article: null,
    plural: null,
    english: "to hit the nail on the head",
    level: "B2",
    meaning: "To describe a problem or situation exactly correctly.",
    exampleDe: "Mit dieser Bemerkung hast du den Nagel auf den Kopf getroffen.",
    exampleEn: "You hit the nail on the head with that comment.",
    category: "idiom",
    notes: "This idiom has a nearly exact English equivalent.",
  },
  {
    word: "die Katze aus dem Sack lassen",
    article: null,
    plural: null,
    english: "to let the cat out of the bag",
    level: "B2",
    meaning: "To reveal a secret, plan, or previously hidden piece of information.",
    exampleDe: "Jetzt lass endlich die Katze aus dem Sack: Was habt ihr geplant?",
    exampleEn: "Now let the cat out of the bag: what have you planned?",
    category: "idiom",
    notes: "The German and English expressions are almost identical.",
  },
  {
    word: "aus allen Wolken fallen",
    article: null,
    plural: null,
    english: "to be completely astonished",
    level: "B2",
    meaning: "To be extremely surprised, usually by unexpected news.",
    exampleDe: "Als ich die Nachricht hörte, fiel ich aus allen Wolken.",
    exampleEn: "When I heard the news, I was completely astonished.",
    category: "idiom",
    notes: "Literally: to fall out of all the clouds.",
  },
  {
    word: "um den heißen Brei herumreden",
    article: null,
    plural: null,
    english: "to beat around the bush",
    level: "B2",
    meaning: "To avoid addressing the main subject directly.",
    exampleDe: "Rede nicht um den heißen Brei herum und sag, was passiert ist.",
    exampleEn: "Don't beat around the bush—say what happened.",
    category: "idiom",
    notes: "Literally: to talk around the hot porridge.",
  },
];
